# main.py
"""
Streamlit app: EcoMind AI – SDG Sustainability Analyzer

Structure:
- Tab 1: Sustainability Analyzer (main)
- Tab 2: Reverse Idea Generator
- Tab 3: About

Privacy: No user data is stored. Uses st.session_state only for temporary values.
All textual outputs are generated by the Gemini API (via gemini.py).

Make sure to set environment variable GOOGLE_API_KEY before running.
"""

import streamlit as st
import os
from typing import List, Dict
import json
from gemini import analyze_sdg, generate_pitch, reverse_ideas
from utils import create_radar_chart, get_sdg_name, summarize_risks

# Page config
st.set_page_config(page_title="EcoMind AI – SDG Sustainability Analyzer", layout="wide", initial_sidebar_state="auto")

# --- Helper UI functions -------------------------------------------------
def check_api_key():
    # Streamlit secrets → preferred
    api_key = st.secrets.get("GOOGLE_API_KEY")

    # Optional fallback: environment variable (if user manually exports it)
    if not api_key:
        api_key = os.environ.get("GOOGLE_API_KEY")

    if not api_key:
        st.sidebar.error(
            "❌ Google API key not found.\n\n"
            "Add it to `.streamlit/secrets.toml` as:\n\n"
            'GOOGLE_API_KEY = "your-key-here"'
        )
        return None

    return api_key


def clear_session_results():
    # remove results we stored
    for k in ["analysis", "pitch", "reverse"]:
        if k in st.session_state:
            del st.session_state[k]

# Small header / branding
st.title("🌱 EcoMind AI — SDG Sustainability Analyzer")
st.markdown("_Analyze projects for Sustainable Development Goal (SDG) alignment using Google Gemini._")

# Sidebar information and controls (visitor-friendly)
with st.sidebar:
    st.header("Quick Info")
    st.markdown("""
- **For visitors:** No setup required — paste your project idea in the main area and click **Analyze**. This hosted instance has the model key configured by the app owner, so you don't need to set any secrets.
- **Privacy:** Analysis runs in-session only. No results are persisted to disk.
- **How it helps:** Get a quick read of which SDGs your idea aligns with, potential risks, feasibility, and AI-generated recommendations.
""")
    st.markdown("---")
    # Sample projects removed to avoid unexpected reruns; visitors can paste their own ideas.
    st.markdown("---")
    if st.button("Clear session outputs", key="clear_session_outputs"):
        clear_session_results()
        st.experimental_rerun()

# Check API key early
api_ok = check_api_key()

# Main tabs
tab1, tab2, tab3 = st.tabs(["Sustainability Analyzer", "Reverse Idea Generator", "About"])

# ----------------------------- Tab 1 -------------------------------------
with tab1:
    st.header("Sustainability Analyzer")
    st.markdown("Paste your project idea or description below. The model will analyze SDG alignment, risks, feasibility and provide recommendations.")

    with st.container():
        project_text = st.text_area("Project description", height=200, placeholder="Enter your project idea, goals, target beneficiaries, technology, and region...", key="project_input")

        cols = st.columns([1,1,1])
        with cols[0]:
            model_choice = st.selectbox("Gemini model", options=["gemini-2.5-flash", "gemini-2.5"], index=0, help="Select the model you want to call.")
        with cols[1]:
            analyze_btn = st.button("Analyze for SDG Alignment", disabled=not api_ok, key="analyze_for_sdg")
        with cols[2]:
            pitch_btn = st.button("Generate Pitch Summary", disabled=True, key="pitch_summary_placeholder")  # enabled after analysis

    st.divider()

    if analyze_btn and project_text.strip():
        with st.spinner("Contacting Gemini and analyzing..."):
            try:
                analysis = analyze_sdg(project_text, model=model_choice)
                # Store in session
                st.session_state["analysis"] = analysis
                st.success("Analysis complete.")
                # enable pitch button
                st.session_state["_can_generate_pitch"] = True
            except Exception as e:
                st.error(f"Analysis failed: {e}")
    # If we have previous analysis in session, show it
    if "analysis" in st.session_state:
        analysis = st.session_state["analysis"]
        sdgs = analysis.get("sdgs", [])
        st.subheader("Matched SDGs")
        if sdgs:
            # Improved, more attractive SDG cards + radar chart
            left, right = st.columns([1,2])
            with left:
                st.markdown("**Top matched SDGs**")
                for s in sdgs:
                    sid = s.get("id")
                    name = s.get("short_name") or get_sdg_name(sid)
                    score = s.get("score", 0) or 0
                    explanation = s.get("explanation", "")
                    # color by score
                    if score >= 75:
                        bg = "#e8f8f0"
                        border = "#27ae60"
                    elif score >= 50:
                        bg = "#fff6e8"
                        border = "#f39c12"
                    else:
                        bg = "#fff0f0"
                        border = "#e74c3c"

                    # Use a high-contrast dark color for the SDG title and percentage so text
                    # remains readable regardless of the chip background.
                    text_color = "#0b2545"
                    chip_html = f"""
<div style='background:{bg};border-left:4px solid {border};padding:10px;border-radius:8px;margin-bottom:8px'>
  <div style='display:flex;align-items:center;justify-content:space-between'>
    <div style='font-weight:700;font-size:15px;color:{text_color}'>{sid} — {name}</div>
    <div style='text-align:right'>
      <div style='font-size:12px;color:#666'>Relevance</div>
      <div style='font-weight:700;font-size:16px;color:{text_color}'>{score}%</div>
    </div>
  </div>
  <div style='margin-top:6px;font-size:13px;color:#333'>{explanation}</div>
  <div style='height:8px;background:#e9ecef;border-radius:6px;margin-top:8px'>
    <div style='width:{min(100, max(0, int(score)))}%;height:100%;background:{border};border-radius:6px'></div>
  </div>
</div>
"""
                    st.markdown(chip_html, unsafe_allow_html=True)

            with right:
                st.markdown("**SDG Relevance Radar**")
                st.plotly_chart(create_radar_chart(sdgs, title="SDG Relevance Radar"), use_container_width=True)
        else:
            st.info("No SDGs detected in the analysis output.")

        # Impact & feasibility
        st.subheader("Impact, Feasibility & Risks")
        imp = analysis.get("sustainability_impact", "Unknown")
        feas = analysis.get("feasibility_score", "N/A")
        risks = analysis.get("risks", {"environmental": [], "social": [], "economic": []})

        # Improved Impact / Feasibility / Risks layout
        def _impact_badge(impact_text: str):
            colors = {"Low": "#e74c3c", "Medium": "#f39c12", "High": "#27ae60"}
            color = colors.get(str(impact_text), "#95a5a6")
            html = f"""
<div style='background:{color};padding:12px;border-radius:8px;color:white'>
  <div style='font-size:13px;font-weight:600'>Predicted Sustainability Impact</div>
  <div style='font-size:20px;font-weight:700;margin-top:6px'>{impact_text}</div>
</div>
"""
            st.markdown(html, unsafe_allow_html=True)

        def _feasibility_widget(score):
            try:
                s = int(float(score))
            except Exception:
                s = 0
            pct = max(0, min(100, int((s / 10.0) * 100)))
            color = "#27ae60" if s >= 7 else ("#f39c12" if s >= 4 else "#e74c3c")
            html = f"""
<div style='padding:8px;border-radius:8px;border:1px solid #eee'>
  <div style='font-size:13px;font-weight:600'>Technical Feasibility (1-10)</div>
  <div style='font-size:20px;font-weight:700;margin-top:6px'>{s}</div>
  <div style='height:12px;background:#e9ecef;border-radius:8px;margin-top:8px'>
    <div style='width:{pct}%;height:100%;background:{color};border-radius:8px'></div>
  </div>
</div>
"""
            st.markdown(html, unsafe_allow_html=True)

        # Layout: impact badge, feasibility bar, and risk cards
        col_imp, col_feat = st.columns([1, 1])
        with col_imp:
            _impact_badge(imp)
        with col_feat:
            _feasibility_widget(feas)

        st.markdown("---")
        st.markdown("**Key Risks**")
        rcols = st.columns(3)
        labels = {"environmental": "Environmental", "social": "Social", "economic": "Economic"}
        for c, key in zip(rcols, ["environmental", "social", "economic"]):
            with c:
                items = risks.get(key, []) if isinstance(risks, dict) else []
                st.markdown(f"**{labels[key]} risks**")
                if items:
                    for it in items:
                        st.write(f"- {it}")
                else:
                    st.write("None identified")

        st.markdown("---")

        # Recommendations
        st.subheader("AI-generated Recommendations")
        recs = analysis.get("recommendations") or []
        if recs:
            for i, r in enumerate(recs, 1):
                st.markdown(f"**{i}.** {r}")
        else:
            st.info("No recommendations returned.")

        # Raw notes (optional)
        notes = analysis.get("notes")
        if notes:
            st.info(notes)

        # Enable pitch generation
        pitch_btn_enabled = True
    else:
        pitch_btn_enabled = False

    # Pitch generation area
    st.divider()
    st.subheader("Pitch Summary")
    pitch_col1, pitch_col2 = st.columns([3,1])
    with pitch_col1:
        if st.button("Generate Pitch Summary", disabled=(not api_ok or "analysis" not in st.session_state), key="generate_pitch_action"):
            # use the same project text and ask Gemini to generate pitch
            with st.spinner("Generating pitch..."):
                try:
                    pitch = generate_pitch(st.session_state.get("project_input") or project_text, model=model_choice)
                    st.session_state["pitch"] = pitch
                    st.success("Pitch generated.")
                except Exception as e:
                    st.error(f"Pitch generation failed: {e}")

        if "pitch" in st.session_state:
            p = st.session_state["pitch"]
            # Styled pitch box
            st.markdown("**Elevator:**")
            st.info(p.get("elevator", ""))
            st.markdown("**Pitch paragraph:**")
            st.write(p.get("pitch", ""))
            st.markdown("**Key bullets:**")
            bullets = p.get("bullet_points", [])
            if bullets:
                for b in bullets:
                    st.write("• " + b)
            # Copy button
            st.code(p.get("pitch", ""), language=None)
            st.download_button("Copy Pitch (download .txt)", data=p.get("pitch",""), file_name="pitch.txt")
    with pitch_col2:
        st.markdown("**Pitch Actions**")
        if "pitch" in st.session_state:
            st.button("Mark as reviewed (session only)", key="mark_reviewed")
        st.markdown("Use the pitch for slide decks, emails, and short funder outreach.")

# ----------------------------- Tab 2 -------------------------------------
with tab2:
    st.header("Reverse Idea Generator")
    st.markdown("Select an SDG and ask EcoMind AI to propose project ideas aligned with that goal.")
    sdg_options = [f"{i} - {get_sdg_name(i)}" for i in range(1, 18)]
    selected = st.multiselect("Choose SDG(s)", options=sdg_options, default=[sdg_options[12]])  # allow multiple selections, default SDG 13
    model_choice = st.selectbox("Gemini model", options=["gemini-2.5-flash", "gemini-2.5"], index=0, key="model_choice_tab2")
    with st.expander("Advanced targeting options (optional)"):
        sector = st.selectbox("Sector / Field", options=["Any","Software","Civil/Infrastructure","Agriculture","Energy","Health","Education","Finance","Other"], index=0, key="rev_sector_tab2")
        region = st.text_input("Region (optional)", placeholder="e.g., East Africa, India, Brazil", key="rev_region_tab2")
        beneficiaries = st.text_input("Primary beneficiaries (optional)", placeholder="e.g., smallholder farmers, urban youth", key="rev_beneficiaries_tab2")
        budget = st.selectbox("Estimated project budget", options=["Any","<$50k","$50k-$200k","$200k-$1M","$1M+"], index=0, key="rev_budget_tab2")
        technologies = st.text_input("Preferred technologies (comma-separated)", placeholder="e.g., AI, IoT, solar", key="rev_tech_tab2")
        constraints = st.text_area("Constraints / priorities (optional)", height=80, placeholder="e.g., no external travel, must be scalable, local manufacturing only", key="rev_constraints_tab2")
    if st.button("Generate Ideas", disabled=(not api_ok or not selected), key="generate_ideas"):
        with st.spinner("Generating ideas from Gemini..."):
            try:
                context = {
                    "sector": None if sector == "Any" else sector,
                    "region": region.strip() if region else None,
                    "beneficiaries": beneficiaries.strip() if beneficiaries else None,
                    "budget": None if budget == "Any" else budget,
                    "technologies": technologies.strip() if technologies else None,
                    "constraints": constraints.strip() if constraints else None,
                }

                per_results = []
                sdg_numbers = [int(sel.split(" - ")[0]) for sel in selected]
                # Generate per-SDG ideas for each selected SDG
                for sdg_number in sdg_numbers:
                    ideas_response = reverse_ideas(sdg_number, model=model_choice, context=context)
                    if isinstance(ideas_response, dict):
                        ideas_response.setdefault("sdg", sdg_number)
                        ideas_response.setdefault("sdg_name", get_sdg_name(sdg_number))
                    per_results.append(ideas_response)

                # Generate combined cross-SDG ideas (if helper available)
                combined_resp = None
                try:
                    from gemini import reverse_ideas_multi
                    combined_resp = reverse_ideas_multi(sdg_numbers, model=model_choice, context=context)
                except Exception:
                    combined_resp = {"covered_sdgs": sdg_numbers, "ideas": [], "raw": "reverse_ideas_multi not available"}

                st.session_state["reverse"] = {"per": per_results, "combined": combined_resp}
                st.success("Ideas generated for each selected SDG and combined cross-SDG ideas.")
            except Exception as e:
                st.error(f"Failed: {e}")

    if "reverse" in st.session_state:
        rev_data = st.session_state["reverse"]
        # Expecting structure: {"per": [...], "combined": {...}}
        per = rev_data.get("per") if isinstance(rev_data, dict) else None
        combined = rev_data.get("combined") if isinstance(rev_data, dict) else None

        # Render per-SDG results
        if per:
            for rev in per:
                sdg_val = rev.get('sdg')
                sdg_label = rev.get('sdg_name') or (get_sdg_name(sdg_val) if isinstance(sdg_val, int) else '')
                st.subheader(f"Ideas for SDG {sdg_val} — {sdg_label}")
                ideas = rev.get("ideas", [])
                if not ideas:
                    st.info("No ideas returned for this SDG.")
                for i, it in enumerate(ideas, 1):
                    t = it.get("title", f"Idea {i}")
                    d = it.get("description", "")
                    with st.expander(f"{i}. {t}"):
                        st.markdown(f"**Description:** {d}")
                        if it.get('why_it_fits'):
                            st.markdown(f"**Why it fits:** {it.get('why_it_fits')}")
                        ks = it.get('key_steps') or []
                        if ks:
                            st.markdown("**Key steps:**")
                            for step in ks:
                                st.write(f"- {step}")
                        if it.get('estimated_budget'):
                            st.markdown(f"**Estimated budget:** {it.get('estimated_budget')}")
                        suggs = it.get('improvement_suggestions') or []
                        if suggs:
                            st.markdown("**Improvement suggestions:**")
                            for s in suggs:
                                st.write(f"- {s}")
                        st.divider()

        # Render combined results
        if combined:
            covered = combined.get('covered_sdgs') or combined.get('sdgs') or []
            if covered:
                covered_label = ", ".join(str(x) for x in covered)
                st.subheader(f"Combined ideas covering SDGs: {covered_label}")
            else:
                st.subheader("Combined ideas")

            ideas = combined.get('ideas', [])
            if not ideas:
                st.info("No combined cross-SDG ideas returned.")
            for i, it in enumerate(ideas, 1):
                t = it.get('title', f"Combined Idea {i}")
                d = it.get('description', "")
                with st.expander(f"{i}. {t}"):
                    st.markdown(f"**Description:** {d}")
                    if it.get('covered_sdgs'):
                        st.markdown(f"**Covers SDGs:** {', '.join(str(s) for s in it.get('covered_sdgs'))}")
                    if it.get('why_it_fits'):
                        st.markdown(f"**Why it fits:** {it.get('why_it_fits')}")
                    ks = it.get('key_steps') or []
                    if ks:
                        st.markdown("**Key steps:**")
                        for step in ks:
                            st.write(f"- {step}")
                    if it.get('estimated_budget'):
                        st.markdown(f"**Estimated budget:** {it.get('estimated_budget')}")
                    suggs = it.get('improvement_suggestions') or []
                    if suggs:
                        st.markdown("**Improvement suggestions:**")
                        for s in suggs:
                            st.write(f"- {s}")
                    st.divider()

# ----------------------------- Tab 3 -------------------------------------
with tab3:
    st.header("About EcoMind AI")
    st.markdown("""
**EcoMind AI – SDG Sustainability Analyzer**

This tool helps innovators and teams quickly evaluate how a project idea aligns with the United Nations Sustainable Development Goals (SDGs). All text analysis is generated by a large language model (Google Gemini) and returned to you in-session only — nothing is persisted.

**How it works**
- You paste a project idea into the Analyzer.
- The app sends the description to Gemini, which returns a structured JSON analysis:
  - A short list of the most relevant SDGs (3–5)
  - Relevance scores (0–100)
  - Brief explanations, risks, feasibility, and recommendations
- The Reverse Idea Generator lets you select an SDG and get 3–5 aligned project concepts.

**Privacy & Safety**
- No user data is stored on disk or sent to third-party services other than the Gemini API.
- Use responsibility: the model output is advisory and should be verified by experts for high-stakes decisions.

**Notes for operators**
- Set environment variable GOOGLE_API_KEY before running.
- The app relies on the Gemini API. API usage may incur charges.
""")
    st.markdown("---")
    st.markdown("**Credits**: Built by EcoMind AI — Gemini-powered sustainability analysis.")

# Footer small note
st.caption("EcoMind AI — All results generated in-session by Gemini. No user data stored.")
